### ISSUE TITLE
TimeTracker obecně - Michal

### ISSUE THREAD

**Issue by Michal1609** [Michal1609/GZTimeTracker#2]
Prostě obecně

Hlavní funkcí je programu je měření času na projektech a jeho reporting.

- Verze .NET CORE 2.2 nebo 3.0?
- MSSQL
- EntityFramework
- Logger
- Web MVC
- komunikace API, verzování
- správa uživatelů, email heslo, facebook, google...
- role
- AutoMapper ano či ne
- Budeme měřit výkon?
- Bootstrap ano či ne? 
- Systray, chtěl bych aby pokud uživatel chce, stáhl appku co poběží v systray a na ní může pouštět a vypínat čas
- - Může fungovat když není online, synchranize by byla online, pokud neprojde, tak čeká a zkouší po X minutách atd. je to služba spouští se při startu
- reporting stráveného času, dodám obrázky o se mě líbí v jiném programu
- free a placená verze (dopředu si určit, po zvážení co to bude umět, jak řešit free a plné verze, jak řešit omezení).
- databáze uživatelů oddělaná od databáze dat (2 fyzické DB)
- export reportingu do csv, pdf, ?xml?
- email a notifikace
- servisní emaily pokud něco přestalo fungovat a je nutný rýchlý zásah na webu nebo programátorů
MVC a Systray + (kdo ví co dalšího, mobilní appka) komunikují přes Oauth API, ta terve z DB
- testy pro API a důležité funkce
- příprava testovacích dat a performace.
- odhad kolik záznamů by tam mohlo být při tolika a tolika uživatelech, spočítat kolik lidí na webohostingu (nějakém) utáhneme.

Členění 1. fáze
- Společnost
- Projekty x Lidi
- Projekt x ukoly

Navrhuju rozvrhnout na více fází, napřed základ, pak přidávat funkionality jako
- kalendář
- náklady (kolik stojí hodina člověk na ukolu)
- další reporting

Projekt: 
- klient pro kterého se dělá
- Jméno prpjektu
- kod projektu
- start a konec projektu (co se stane mimo datum)
- typ projektu (zatím neřešit, týká se toho jak tam běží peníze, budgety, hodinovky lidí atd.)
- oprávnění - kdo uvidí reporty, admini, manageři, lidi? 
- projekt je možné editivat, mazat, kopírovat

Projekt má  tásky
- Název tásku
- payable (zatím ne)

Projekt má team lidí
- člověk může být manager (uvidí víc reportů atd)

Podpora více jazyků, pozor na časová pásma atd. Nechceme se soustředit pouze na ČR

Struktura projektu podle stabndardu Infrastructure, Core, Web viz https://github.com/ardalis/CleanArchitecture/blob/master/README.md

**Comment by avokiz** [comment]
Omezení free verze:
- pouze jeden uživatel (sám k sobě s maximálním oprávněním)
- omezený pořet projektů/úkolů (např. max. 10 projektů, celkem max. 100 úkolů)
- omezená doba uchovávání aktivních dat (např. max. 2-3 měsíce, starší se smažou)
- omezený výběr reportů (jen co má smysl pro jednoho uživatele)
- bez uchovávání reportů (vyjede report na obrazovku, vyexportuje např. do PDF, ale neukládá se do DB)

**Comment by Metziell** [comment]
AutoMapper - pokud z toho nebudem chtít udělat multifunkční monstrozitu, tak asi jo
Performance monitoring - minimálně bysme s tím měli počítat do budoucna
Více jazyků - pro začátek bude stačit (čeština a) angličtina, s ostatníma si sami neporadíme
Časová pásma - ukládat v jednotném pásmu, při čtení/ukládání přepočítat...?

**Comment by Michal1609** [comment]
Ten automaper taky může dělat problém, ale využil bych. Aspon se ho s ním seznámíme.
PerfMon - do budoucna OK
Více jazýku, CZ a ENG, spíš jde o to, jak s nimi pracovat. Tahat je z DB? Nebo z Resources? Lokalozace dle domény, nebo někde na hoře webu ikona na zvolení jazyka?
Časová pásma. Asi UTC a pak přepočítávat k zoně toho kdo se dívá. Mělo by se dát někde vyčíst. Ale i to můžeš udělat problém. Uvidíme.
