### ISSUE TITLE
TimeTracker obecně - Petr

### ISSUE THREAD

**Issue by Metziell** [Michal1609/GZTimeTracker#4]

**Comment by Metziell** [comment]
Nejdřív web API + aplikace
Později smartphone app pro Android i iOS a desktop app

**Comment by Metziell** [comment]
**Technologie**
- určitě .NET Core 3.0 (podporuje .NET Standard 2.1)
- DIC - jaký kontejner?
- REST API
- ověřování přes OAuth2
- ...jinak souhlasím s Michalem

**Comment by Metziell** [comment]
**Funkce**
- vykazování času 
  - start-stop
  - manuální vložení času - **speciální oprávnění? - premium?**
- členění výkazů
  - aktivita
  - člověk
  - typ aktivity / tag (vývoj, administrace, komunikace se zákazníky, ...) - **premium?**
  - projekt
- přehledy
  - každý si může zobrazit přehled svých aktivit
  - nadřízený uvidí i přehledy svých podřízených
  - filtrování přehledů podle členění
  - grafy, tabulky
  - export - plain text, pdf, Excel, (xml/json?)
- historie akcí
- role
- externí login pro servisní zásahy
- formátování textu aktivit - **premium?**
  - markdown?
- přikládání souborů / obrázků k aktivitám? - **premium?**
- konfigurace barviček
  - jednotné téma v rámci projektu
  - vlastní témata - **premium**

**Comment by Metziell** [comment]
**Logo programu** - Lenička navrhuje papouška

**Comment by Metziell** [comment]
Free verze do určitého počtu uživatelů, aktivních projektů
Premium - cena podle počtu uživatelů?

**Comment by Michal1609** [comment]
> 
> 
> **Technologie**
> 
>     * určitě .NET Core 3.0 (podporuje .NET Standard 2.1)
> 
>     * DIC - jaký kontejner? - .NET CORE má DIC v sobě, není třeba přemýšlet o ničem jiném
>   
>     * REST API
> 
>     * ověřování přes OAuth2
> 
>     * ...jinak souhlasím s Michalem

**Comment by Michal1609** [comment]
- DIC - jaký kontejner?
.NET CORE má DIC v sobě, není třeba se dívat po jiném

- vykazování času -start-stop-pauza
 Osobně bych byl pro Start/Stop. Je to jedno tlačítko a nejde se splést. 

- Grafy
 Podle využití asi https://www.chartjs.org 

- Historie akcí
 co tím básník myslí?

- externí login pro servisní zásahy
 Co tím básník myslí?

-přikládání souborů / obrázků k aktivitám?
 Nic takového bych nedělal, odkláníme se od produktu na měření času a snažíme se pak pomalu fušovat do programů na projektové řízení. To může být dálší fáze jít směrem jako EasyProject

- Konfigurace barviček
 Do budoucna, ale myslet na to, že mohou být témata od začátku. Dříve ASP. NET mělo vyložene Templatas složku pro webovky atd, tad to bude chtít prostuodvovat jak se v CORE tohle dělá. Zatím nevím, ale chce to s tím začít dělat aby pak nebyla velké předělávka.

- Logo
 Prozatím bych logo neřešil, to jsem dělal tolikrát a strávil nad tím tolik času, že výsledek je ten, že děláš několik, dní logo a na práci se nesáhne a nakonec se nic neudělá. Řešil bych si sart s tím, že tam logo jako takové být nemusí, případně ejn značka firmy a ta je hotová. Taky uvidíme podle vzhledu co z nás vypadne, pak sde dá logo přizpůsobit. Když uděláš nejdřív logo, tak všechnu grafiku cpeš tak, aby to sedělo k logu a né naopak.

Budeš mít ještě něco? Nebo to mám hodit do toho jednoho tasku a Wiki jako resumé. Pak budeme řešit dál.

**Comment by Metziell** [comment]
Historie akcí - Doslova kdy kdo co udělal, případně pak odkud (web/desktop/mobil). Možná by mohlo stačit u každé věci mít CreateDate, CreatedBy, LastModified, ModifiedBy

Externí login - asi síla zvyku z on-premise applikací :D na webu to asi není potřeba, odvolávám

Konfigurace barviček - Jop, něco takovýho jsem měl na mysli

**Comment by Metziell** [comment]
Teď mě už nic dalšího nenapadá. Kdyžtak to pak přidám do wiki.

**Comment by Michal1609** [comment]
Historie akcí super. Byl bych pro. Musíme ale myslet na jednu věc,a  to je počet záznamů, co se tam může generovat. Chce to trochu napočítat, ale obecně, máme 100 free uživatelů,. každá denně udělá 20 záznamů. To je 2 000 záznamů za den, to je 730 000 za rok. Takže tam budou tabule, co budou hodně bobtnat, a budeme muset držet jen  nějakou historii atd, aby sme se výkonově nedostali někam do prčic.
